import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { NavBar } from "@/components/NavBar";
import { cookies } from "next/headers";

import { LogOut } from "@/components/LogOutButton";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

// async to get cookies
export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const cookieStore = await cookies();

	const token = cookieStore.has("token");
	return (
		// disabling the problem with hydration
		<html lang="en" suppressHydrationWarning>
			<body
				// className={`${geistSans.variable} ${geistMono.variable} antialiased`}
				// everything in a flex-col, min-h-screen minimum of the screen but can go beyond, h-full well 100% of the parent so gonna delete it
				className=" flex flex-col  min-h-screen ">
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange>
						
					{token && (
						<>
							<NavBar />

							<div className="ml-5 mb-5">
								<LogOut></LogOut>
							</div>
						</>
					)}

					{/* flex-1 says take all the space that is left (navbar has his own height and popping also, ex if navbar and poppoing are 100px both and the screen is 900px children will take 800px), flex col yeah also vertical. min-h-0 means you can cut your height given by the flexbox  */}
					<main className="flex-1 flex flex-col min-h-0 ">{children}</main>
				</ThemeProvider>
			</body>
		</html>
	);
}
